// <auto-generated />
using HomeMusicLibrary.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeMusicLibrary.Core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HomeMusicLibrary.Core.Model.AlbumsTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlbumId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RealiseDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("int");

                    b.Property<string>("TypeAlbum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AlbumsTables");
                });

            modelBuilder.Entity("HomeMusicLibrary.Core.Model.AlbumTracksTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlbumId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TracksTables");
                });

            modelBuilder.Entity("HomeMusicLibrary.Core.Model.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
